import 'dart:developer';
import 'dart:typed_data';
import 'package:firebase_ai/firebase_ai.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import '../input_page/models/form_input.dart';

class GreetingService {
  final GenerativeModel model;

  GreetingService({GenerativeModel? model})
      : model = model ??
            FirebaseAI.googleAI() // TODO: Add appCheck to secure your requests
                .generativeModel(
              model: 'gemini-2.5-flash-image-preview',
              // Configure the model to respond with text and images
              generationConfig: GenerationConfig(responseModalities: [
                ResponseModalities.text,
                ResponseModalities.image
              ]),
            );

  Future<(String?, Uint8List?)> generateGreeting(FormInput input) async {
    final prompt = [
      Content.text('''
      You are an expert at crafting warm and sincere greeting messages.
      Write a ${input.tone}-toned greeting message for ${input.occasion} occasion.
      Recipient details: Their name is ${input.recipientName}${input.age != null ? ', age ${input.age}' : ''}.'
      '${input.additionalNotes != null ? 'Additional context: ${input.additionalNotes}.' : ''}
      
      Rules:
      Keep the message short (maximum of two sentences).
      Match the tone scale, where 0.0 is very casual and 1.0 is very formal.
      Be specific by incorporating the provided personal details.
      Maintain sincerity and warmth at all times.
      Consider both the occasion and the recipient’s personal context.
      
      Create cute background image to go alongside the text, I will put text 
      on it by myself, so make sure it's only graphic elements. The image 
      should have minimal, elegant design with main subject in the center.
      ''')
    ];

    String? text;
    Uint8List? imageBytes;

    try {
      final response = await model.generateContent(prompt);

      // Handle the generated text and image
      final parts = response.candidates.firstOrNull?.content.parts;

      if (parts != null && parts.isNotEmpty) {
        for (final part in parts) {
          if (part is TextPart) {
            text = part.text;
            log('\n🤖 Generated text: $text', name: 'GreetingService');
          }
          if (part is InlineDataPart) {
            imageBytes = part.bytes;
            log('\n🤖 Generated image of size: ${imageBytes.length} bytes',
                name: 'GreetingService');
          }
        }
      } else {
        log('❌ Error: No content generated by the model.',
            name: 'GreetingService');
      }
    } catch (e) {
      log('❌ Error generating greeting: $e', name: 'GreetingService');
    }
    return (text, imageBytes);
  }
}
